# Config files for remote training

# Directories
DIR:
  DATASET: '/code/dataset_local_v9/training'  #  directory of your training dataset

# Split files
SPLIT:
  TRAIN: '/code/dataset_local_v9/training_lists/all_train.txt'  # training lists of your training set
  VAL: '/code/dataset_local_v9/training_lists/all_val.txt'  # training lists of your validation set
  LEFT: '0128_irL_kuafuv2_half.png'
  LEFT_NO_IR: '0128_irL_kuafu_half_no_ir.png'
  RIGHT: '0128_irR_kuafuv2_half.png'
  RIGHT_NO_IR: '0128_irR_kuafu_half_no_ir.png'
  DEPTHL: 'depthL.png'
  DEPTHR: 'depthR.png'
  META: 'meta.pkl'
  LABEL: 'irL_label_image.png'

# Configuration for testing on real dataset
REAL:
  DATASET: '/code/real_dataset_local_v9'  # path to your real testing dataset
  LEFT: '1024_irL_real_1080.png'
  RIGHT: '1024_irR_real_1080.png'

# Solver args
SOLVER:
  LR_CASCADE: 0.001                         # base learning rate for cascade
  LR_G: 0.0002                              # base learning rate for G
  LR_D: 0.0002                              # base learning rate for D
  LR_STEPS: '5000,6000,7000,8000,9000:2'    # the steps to decay lr: the downscale rate
  STEPS: 10000                              # number of steps to train
  EPOCHS: 1
  BATCH_SIZE: 1                             # batch size
  NUM_WORKER: 1                             # num_worker in dataloader

# Model parameters
ARGS:
  MAX_DISP: 192             # maximum disparity
  MODEL: 'gwcnet-c'
  GRAD_METHOD: 'detach'
  NDISP: (48, 24)           # ndisps
  DISP_INTER_R: (4, 1)      # disp_intervals_ratio
  DLOSSW: (0.5, 2.0)        # depth loss weight for different stage
  CR_BASE_CHS: (32, 32, 16) # cost regularization base channels
  USING_NS: True            # using neighbor search
  NS_SIZE: 3                # nb_size
  CROP_HEIGHT: 256          # crop height
  CROP_WIDTH: 512           # crop width

# Data augmentation
DATA_AUG:
  # Color jitter
  BRIGHT_MIN: 0.4
  BRIGHT_MAX: 1.4
  CONTRAST_MIN: 0.8
  CONTRAST_MAX: 1.2

  # Gaussian blur
  GAUSSIAN_MIN: 0.1
  GAUSSIAN_MAX: 2.0
  GAUSSIAN_KERNEL: 9